export const WORDS: { word: string, category: string }[] = [
    // Еда (Food)
    { word: 'apple', category: 'Food' },
    { word: 'banana', category: 'Food' },
    { word: 'carrot', category: 'Food' },
    { word: 'chocolate', category: 'Food' },
    { word: 'coffee', category: 'Food' },
    { word: 'cookie', category: 'Food' },
    { word: 'grape', category: 'Food' },
    { word: 'hamburger', category: 'Food' },
    { word: 'honey', category: 'Food' },
    { word: 'icecream', category: 'Food' },
    { word: 'lemon', category: 'Food' },
    { word: 'milk', category: 'Food' },
    { word: 'orange', category: 'Food' },
    { word: 'pizza', category: 'Food' },
    { word: 'strawberry', category: 'Food' },
    { word: 'sugar', category: 'Food' },
    { word: 'tea', category: 'Food' },
    { word: 'tomato', category: 'Food' },
    { word: 'watermelon', category: 'Food' },

    // Животные (Animals)
    { word: 'alligator', category: 'Animals' },
    { word: 'bear', category: 'Animals' },
    { word: 'butterfly', category: 'Animals' },
    { word: 'camel', category: 'Animals' },
    { word: 'cheetah', category: 'Animals' },
    { word: 'dolphin', category: 'Animals' },
    { word: 'eagle', category: 'Animals' },
    { word: 'elephant', category: 'Animals' },
    { word: 'giraffe', category: 'Animals' },
    { word: 'kangaroo', category: 'Animals' },
    { word: 'leopard', category: 'Animals' },
    { word: 'lion', category: 'Animals' },
    { word: 'monkey', category: 'Animals' },
    { word: 'octopus', category: 'Animals' },
    { word: 'owl', category: 'Animals' },
    { word: 'penguin', category: 'Animals' },
    { word: 'rhinoceros', category: 'Animals' },
    { word: 'shark', category: 'Animals' },
    { word: 'tiger', category: 'Animals' },
    { word: 'whale', category: 'Animals' },

    // Профессии (Professions)
    { word: 'accountant', category: 'Professions' },
    { word: 'architect', category: 'Professions' },
    { word: 'artist', category: 'Professions' },
    { word: 'chef', category: 'Professions' },
    { word: 'doctor', category: 'Professions' },
    { word: 'engineer', category: 'Professions' },
    { word: 'farmer', category: 'Professions' },
    { word: 'firefighter', category: 'Professions' },
    { word: 'lawyer', category: 'Professions' },
    { word: 'nurse', category: 'Professions' },
    { word: 'pharmacist', category: 'Professions' },
    { word: 'photographer', category: 'Professions' },
    { word: 'pilot', category: 'Professions' },
    { word: 'plumber', category: 'Professions' },
    { word: 'scientist', category: 'Professions' },
    { word: 'teacher', category: 'Professions' },
    { word: 'veterinarian', category: 'Professions' },
    { word: 'writer', category: 'Professions' },

    // Природа (Nature)
    { word: 'avalanche', category: 'Nature' },
    { word: 'blizzard', category: 'Nature' },
    { word: 'canyon', category: 'Nature' },
    { word: 'cliff', category: 'Nature' },
    { word: 'desert', category: 'Nature' },
    { word: 'earthquake', category: 'Nature' },
    { word: 'forest', category: 'Nature' },
    { word: 'glacier', category: 'Nature' },
    { word: 'hurricane', category: 'Nature' },
    { word: 'island', category: 'Nature' },
    { word: 'mountain', category: 'Nature' },
    { word: 'ocean', category: 'Nature' },
    { word: 'rainbow', category: 'Nature' },
    { word: 'river', category: 'Nature' },
    { word: 'sunrise', category: 'Nature' },
    { word: 'sunset', category: 'Nature' },
    { word: 'tornado', category: 'Nature' },
    { word: 'volcano', category: 'Nature' },
    { word: 'waterfall', category: 'Nature' },
    { word: 'whirlwind', category: 'Nature' },

    // Технологии (Technology)
    { word: 'algorithm', category: 'Technology' },
    { word: 'application', category: 'Technology' },
    { word: 'browser', category: 'Technology' },
    { word: 'computer', category: 'Technology' },
    { word: 'cybersecurity', category: 'Technology' },
    { word: 'database', category: 'Technology' },
    { word: 'encryption', category: 'Technology' },
    { word: 'hardware', category: 'Technology' },
    { word: 'internet', category: 'Technology' },
    { word: 'keyboard', category: 'Technology' },
    { word: 'laptop', category: 'Technology' },
    { word: 'microprocessor', category: 'Technology' },
    { word: 'network', category: 'Technology' },
    { word: 'password', category: 'Technology' },
    { word: 'robotics', category: 'Technology' },
    { word: 'software', category: 'Technology' },
    { word: 'technology', category: 'Technology' },
    { word: 'username', category: 'Technology' },
    { word: 'virtual', category: 'Technology' },
    { word: 'website', category: 'Technology' },

    // Прочее (Miscellaneous)
    { word: 'adventure', category: 'Miscellaneous' },
    { word: 'balloon', category: 'Miscellaneous' },
    { word: 'bicycle', category: 'Miscellaneous' },
    { word: 'birthday', category: 'Miscellaneous' },
    { word: 'chess', category: 'Miscellaneous' },
    { word: 'climate', category: 'Miscellaneous' },
    { word: 'curiosity', category: 'Miscellaneous' },
    { word: 'dinosaur', category: 'Miscellaneous' },
    { word: 'festival', category: 'Miscellaneous' },
    { word: 'galaxy', category: 'Miscellaneous' },
    { word: 'history', category: 'Miscellaneous' },
    { word: 'imagination', category: 'Miscellaneous' },
    { word: 'jewelry', category: 'Miscellaneous' },
    { word: 'kitchen', category: 'Miscellaneous' },
    { word: 'language', category: 'Miscellaneous' },
    { word: 'meditation', category: 'Miscellaneous' },
    { word: 'notebook', category: 'Miscellaneous' },
    { word: 'origami', category: 'Miscellaneous' },
    { word: 'puzzle', category: 'Miscellaneous' },
    { word: 'rainbow', category: 'Miscellaneous' }
];


export const KEYBOARD_LETTERS:string[] = Array.from('ABCDEFGHIJKLMNOPQRSTUVWXYZ');
